language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - p7zip-full
install: true
script: travis/build.sh
before_deploy: "chmod +x travis/deploy.sh"
deploy:
  provider: script
  script: travis/deploy.sh
  on:
    branch: master_simulation
  skip_cleanup: true
branches:
  except:
    - master